### PR TITLE
Adds support for listening to PHP console errors

### PR DESCRIPTION
**Pull request by luceos**
**don't merge, depends on https://github.com/flarum/core/pull/1810**

Relates to flarum/core#1789 this shows a possible implementation for hooking into console events.

### CODE REVIEW

**Comment by dsevillamartin** [comment]
This rebase did not work. Is this ready for merge? If so, could you PR it again lol 🙈 what happened here.

**Comment by luceos** [comment]
Omg what happened here! I seriously need to start from scratch now 🤦‍♂

**Comment by davwheat** [comment]
Just for prosterity: one issue I forsee with this is that when you create codeblocks in Flarum, hljs throws errors about while you're typing the language

e.g., while you're writing ```javascript, you'd write ```javasc at one point, which HLJS would try to highlight, but obviously no "javasc" language exists, so it errors to the console.

Sentry would end up fillllled with these errors.

**Comment by dsevillamartin** [comment]
Isn't this already a thing? There's already an option for JS errors 🤔

**Comment by davwheat** [comment]
Yeah I noticed that a few hours after... We can close this then, right?

**Comment by dsevillamartin** [comment]
oh i think this is PHP console, not JS console...

**Comment by davwheat** [comment]
OH!

**Comment by luceos** [comment]
Closing this one, I also think console errors are automatically logged.

**Comment by dsevillamartin** [comment]
I don't think we log PHP console errors? Not entirely sure.

**Pull request closed without merging**
